# -*- coding: utf-8 -*-
"""Kurzbeschreibungen (deutsch, ASCII) je Pokemon (Gen 1+2) fuer die
Galerie-Detailansicht. Automatisch geholt von PokeAPI, auf ASCII
transliteriert (GFX-Font hat keine Umlaute). Neu erzeugen mit
tools/fetch_dex_desc.py.
"""

DESC = {
    1: "Dieses Pokemon traegt von Geburt an einen Samen auf dem Ruecken, der mit ihm keimt und waechst.",
    2: "Es traegt eine Knospe auf seinem Ruecken. Nimmt es Nahrung zu sich, soll aus der Knospe eine grosse bluehende Blume werden.",
    3: "Es spreizt die breiten Blaetter seiner Bluete, um seinen Koerper mit Sonnenenergie zu durchfluten.",
    4: "Die Flamme auf seiner Schweifspitze zeigt die Lebensenergie an. Ist es gesund, leuchtet sie hell.",
    5: "Es schlaegt im Kampf mit seinem Schwanz nach seinen Gegnern. Anschliessend zerfetzt es die Gegner mit seinen scharfen Klauen.",
    6: "Wenn dieses Pokemon einen Strahl gluehenden Feuers speit, leuchtet seine Schwanzspitze auf.",
    7: "Es zieht sich in seinen Panzer zurueck und greift dann mit Wasserstrahlen seine Gegner an.",
    8: "Bei Gefahr zieht dieses Pokemon seinen Kopf ein. Die Schwanzspitze ragt jedoch aus dem Panzer heraus.",
    9: "Es begraebt seine Gegner mit seinem enormen Koerpergewicht. Wenn es in einer aussichtslosen Lage steckt, zieht es sich in seinen Panzer...",
    10: "Als Schutz vor Feinden sondert es einen uebel riechenden Gestank mit seinen Antennen ab.",
    11: "Der stahlharte Panzer schuetzt seinen zarten Koerper. Es wartet geduldig auf seine Entwicklung.",
    12: "Es liebt Bluetenhonig. Es findet selbst Blumen, die sehr wenig Pollen haben.",
    13: "Es lebt bevorzugt in Waeldern und in hohem Gras. Auf dem Kopf traegt es einen circa 5 cm langen, spitzen, giftigen Stachel.",
    14: "Dieses Pokemon kann sich kaum bewegen. Bei drohender Gefahr verhaertet es seinen Panzer.",
    15: "Dieses Pokemon verfuegt ueber drei Giftstachel. Es kann seine Gegner damit wiederholt stechen.",
    16: "Ein vorwiegend in Waeldern lebendes Pokemon, das zur Verteidigung mit den Fluegeln Sand aufwirbelt.",
    17: "Die Krallen an seinen Fuessen sind sehr ausgepraegt. Es kann sogar ein Owei zu seinem Nest in 100 km Entfernung tragen.",
    18: "Dieses Pokemon schnellt bei der Jagd blitzschnell unter Wasser, um seine ahnungslose Beute zu fangen.",
    19: "Es baut sein Nest, wo es Futter findet. Es ist den ganzen Tag auf der Suche nach etwas Essbarem.",
    20: "Es wetzt seine staendig wachsenden Zaehne an harten Dingen. Es kann Waende aus Beton zernagen.",
    21: "Es beschuetzt sein Gebiet stets vor Eindringlingen. Daher fliegt es staendig wild umher.",
    22: "Mit seinen riesigen Fluegeln kann dieses Pokemon nahezu pausenlos in der Luft bleiben.",
    23: "Mit dem Alter wird der Koerper dieses Pokemon immer laenger. Es schlaeft um Aeste gewickelt.",
    24: "Das Muster auf seinem Bauch aehnelt einer Fratze. Schwache Gegner nehmen bereits beim Anblick Reissaus.",
    25: "Es streckt seinen Schweif nach oben, um seine Umgebung zu pruefen. Haeufig faehrt ein Blitz hinein.",
    26: "Wenn es sich auflaedt, zucken seine Muskeln und es wird aggressiver und kampflustiger.",
    27: "Es graebt und lebt im Erdboden. Bei Gefahr rollt es sich zum Schutz zu einem Ball zusammen.",
    28: "Wenn es schnell graebt, koennen seine Stacheln und Krallen abbrechen. Sie wachsen binnen eines Tages nach.",
    29: "Dieses Pokemon ist sehr klein, verfuegt aber ueber starke Gifte. Das Weibchen hat ein kleineres Horn.",
    30: "Das Weibchen ist ausgeglichener. Es stoesst Schreie im Ultraschallwellenbereich aus, die den Gegner verwirren koennen.",
    31: "Es benutzt seinen schuppigen Koerper, um den Hoehleneingang als Schutz fuer seine Jungen zu sperren.",
    32: "Es untersucht die Umgebung, indem es die Ohren spitzt und lauscht. Sein giftiges Horn schuetzt es.",
    33: "Es ueberwacht mit seinen riesigen Ohren die Umgebung. Registriert es eine Bewegung, greift es an.",
    34: "Seine steinharte Haut und sein ausgepraegtes Horn sind seine Markenzeichen. Achte auf das Horn, denn es enthaelt Gift.",
    35: "Eine Ansammlung von Piepi bei Vollmond tanzen zu sehen, soll Freude verheissen.",
    36: "Es kann eine Nadel hoeren, die in 1 km Entfernung zu Boden faellt. Es lebt in der Stille der Berge.",
    37: "Dieses Pokemon hat bei seiner Geburt nur einen Schweif, der sich mit zunehmendem Alter aufspaltet.",
    38: "Es hat neun lange Schweife und sein Fell glaenzt guelden. Man sagt, es soll 1 000 Jahre alt werden.",
    39: "Es fesselt die Gegner mit seinen grossen, runden Augen und versetzt sie in Schlaf, indem es eine beruhigende Melodie singt.",
    40: "Sein Fell ist so flauschig, dass, wenn zwei zusammenstehen, sie nicht getrennt werden moechten.",
    41: "Obwohl es keine Augen hat, kann es Hindernisse mithilfe von Ultraschallwellen wahrnehmen.",
    42: "Dieses Pokemon saugt dem Gegner selbst dann noch Energie ab, wenn es zu schwer zum Fliegen wird.",
    43: "Tagsueber versteckt es sich in der kalten Erde, um die Sonne zu meiden. Es waechst im Mondschein.",
    44: "Dieses Pokemon sondert einen uebelriechenden Geruch ab. Trotzdem halten einige Leute es im Haus.",
    45: "Je groesser die Bluetenblaetter, desto mehr giftige Pollen sind in der Bluete enthalten.",
    46: "Auf seinem Ruecken wachsen Pilze, die man Tochukaso nennt. Die Pilze wachsen mit ihrem Wirt.",
    47: "Parasek wird von einem Pilz, der groesser als das Pokemon ist, kontrolliert. Er gibt Giftsporen ab.",
    48: "Seine grossen Augen bestehen aus vielen kleinen Augen. Nachts wird es von Licht angezogen.",
    49: "Wer die von ihm verstreuten Schuppen beruehrt, wird gelaehmt und muss sich setzen.",
    50: "Dieses Pokemon lebt 1 m unter der Erde. Es frisst Wurzeln und kommt selten an die Oberflaeche.",
    51: "Im Kampf graebt es sich ein und attackiert den Gegner aus einer unvorhersehbaren Richtung.",
    52: "Ein nachtaktives Pokemon. Sieht es etwas Schimmerndes, fangen seine Augen an zu glaenzen.",
    53: "Dieses Pokemon hat sehr schoenes Fell. Es ist jedoch ein schwer erziehbares Haustier.",
    54: "Es wird permanent von Kopfschmerzen geplagt. Wird der Schmerz staerker, setzt es geheimnisvolle Kraefte ein.",
    55: "Es taucht bei Sonnenuntergang am Wasser auf. Leuchtet seine Stirn, setzt es telekinetische Kraefte ein.",
    56: "Da es grundlos angreift und nicht zwischen Freund oder Feind unterscheidet, ist es sehr gefaehrlich.",
    57: "In ganz seltenen Faellen beruhigt sich dieses sehr jaehzornige Pokemon und ist fuer einen Moment friedlich.",
    58: "Es ist sehr freundlich und bleibt den Menschen treu. Durch Bellen und Beissen versucht es, Gegner zu verscheuchen.",
    59: "Dieses Pokemon traegt ein wunderschoenes Fell. Es ist obendrein schnell und sehr wendig.",
    60: "Seine glatte, schwarze Haut ist duenn und feucht. Teilweise sind seine Innereien als spiralfoermige Muster sichtbar.",
    61: "Dieses Pokemon kann im Wasser und auch an Land leben. An Land schwitzt es sich den Koerper nass.",
    62: "Es hat extrem starke Muskeln und kann durch den Ozean schwimmen, ohne sich ausruhen zu muessen.",
    63: "Es schlaeft 18 Stunden am Tag. Waehrenddessen setzt es eine Vielzahl zusaetzlicher sensorischer Kraefte ein.",
    64: "Setzt es seine Psycho-Kraefte ein, sondert es Alphawellen ab, die Praezisionsgeraeten schaden koennen.",
    65: "Seine Gehirnzellen vervielfachen sich sein ganzes Leben lang. Daher kann es sich immer an alles erinnern.",
    66: "Es hebt Georok hoch, um seinen Koerper zu trainieren. Ausserdem uebt es sich in jeder Art von Kampfsport.",
    67: "Dieses Pokemon ist superstark. Es kann sich nur mit einem Kraft regulierenden Guertel bewegen.",
    68: "Seine markigen Arme koennen innerhalb von nur zwei Sekunden 1 000 Schlaege verteilen.",
    69: "Obwohl sein Koerper sehr schmal ist, schnappt es blitzschnell nach Beute.",
    70: "Die Blaetter werden eingesetzt, um Gegner aufzuschlitzen. Dieses Pokemon spuckt eine Fluessigkeit, die alles aufloest.",
    71: "Dieses Pokemon soll in grossen Kolonien tief im Dschungel leben, doch niemand kann dies bestaetigen.",
    72: "Sein Koerper besteht aus Wasser. Aus seinen kristallartigen Augen verschiesst es eigenartige Strahlen.",
    73: "Dieses Pokemon kann die Tentakel bei der Jagd ausfahren, um die Beute leichter zu fangen.",
    74: "Wanderer stolpern in den Bergen haeufig ueber dieses Pokemon, da es wie ein Stein aussieht.",
    75: "Es ist ihm voellig gleichgueltig, wenn Stuecke aus ihm herausbrechen, waehrend es Berge hinabrollt.",
    76: "Sie rollen Berge hinunter und hinterlassen Spurrillen. Halte dich von diesen Rillen fern.",
    77: "Neugeboren kann es kaum stehen. Durch das Galoppieren werden seine Beine aber schneller und kraeftiger.",
    78: "Dieses Pokemon verfolgt schnelle Objekte in der Hoffnung, ein Wettrennen gegen sie zu gewinnen.",
    79: "Es ist stets in Gedanken versunken und niemand weiss, worueber es nachdenkt. Es kann mit seiner Rute gut angeln.",
    80: "Das Muschas an seiner Rute laesst nicht locker, da ein leckerer Geschmack aus seiner Rute stroemt.",
    81: "Die Magneten an seinem Koerper erzeugen ein Antigravitationsfeld, um es staendig in der Schwebe zu halten.",
    82: "Schliessen sich mehrere Magnetilo zusammen, entsteht dieses Pokemon. Es entlaedt kraeftige Hochspannungsmagnetwellen.",
    83: "Dieses Pokemon nutzt eine Lauchstange als Waffe. Es setzt sie wie ein Schwert ein.",
    84: "Dieses zweikoepfige Pokemon gilt als ploetzliche Mutation. Es rennt bis zu 100 km/h schnell.",
    85: "Laesst ein Feind auch nur einen der drei Koepfe fuer nur eine Sekunde aus den Augen, wird er sofort gepickt.",
    86: "Dieses Pokemon lebt auf Eisbergen. Es schwimmt im Eiswasser und bricht das Eis mithilfe seines Horns.",
    87: "Sein Koerper ist mit reinem, weissem Fell ueberzogen. Je kaelter es wird, desto aktiver wird dieses Pokemon.",
    88: "Schlamm, der Roentgenstrahlung vom Mond ausgesetzt war, wurde zu Sleima. Es isst am liebsten dreckige Dinge.",
    89: "Sie treffen sich an stinkenden Orten, an denen der Schleim sich tuermt. Dies merkt man am Gestank.",
    90: "Eine harte Schale schuetzt dieses Pokemon. Nur wenn es diese oeffnet, wird es verwundbar.",
    91: "Austos, die im Meer mit starker Stroemung leben, werden gross und entwickeln scharfe Stacheln.",
    92: "Es hat einen gasfoermigen Koerper. Es kann jeden Gegner mit Giftgas einnebeln und dadurch ersticken.",
    93: "Falls du im Dunkeln das Gefuehl hast, beobachtet zu werden und niemand ist zu sehen, ist es bestimmt Alpollo.",
    94: "Es versteckt sich im Schatten. Man sagt, wenn sich ein Gengar versteckt, kuehlt es sich um 5 Grad ab.",
    95: "Dieses Pokemon graebt auf seiner Suche nach Futter lange Tunnel, in denen sich spaeter Digda einnisten.",
    96: "Traumato versetzt Gegner in den Schlaf und frisst deren Traeume. Von Alptraeumen wird ihm aber uebel.",
    97: "Es traegt ein Pendel. Man berichtet von einem Vorfall, bei dem es ein Kind mitnahm, das es zuvor hypnotisiert hatte.",
    98: "Wittert es Gefahr, huellt es sich in Blasen aus seinem Maul, um groesser zu erscheinen.",
    99: "Die Kraft seiner grossen und harten Schere entspricht 10 000 PS. Durch die Groesse ist sie aber auch aeusserst unhandlich und sperrig.",
    100: "Es wurde entdeckt, als man Pokebaelle einfuehrte. Es scheint, als gaebe es da einen Zusammenhang.",
    101: "Es explodiert schon bei kleinsten Reizen. Sein Spitzname \"Die Bombenkugel\" spiegelt die Furcht der Menschen wider.",
    102: "Die sechs Eier kommunizieren telepathisch. Werden sie getrennt, finden sie sich schnell wieder.",
    103: "Seine drei Koepfe denken unabhaengig voneinander. Dennoch sind sie nett zueinander und streiten nie.",
    104: "Es traegt den Schaedel seiner verstorbenen Mutter auf seinem Kopf. Fuehlt es sich einsam, soll es laut weinen.",
    105: "Es ist klein und war urspruenglich sehr schwach. Erst als es anfing Knochen einzusetzen, wurde es wild.",
    106: "Die Beine ziehen und strecken sich unabhaengig voneinander. Mit seinen dehnbaren Beinen kann es einen entfernten Gegner treffen.",
    107: "Die Schlaege, die es austeilt, koennen Beton pulverisieren. Es muss sich im Kampf alle drei Minuten ausruhen.",
    108: "Seine Zunge ist mit klebrigem Speichel bedeckt, der ueberall haftet. Dies ist sehr nuetzlich.",
    109: "Sein duenner, ballonartiger Koerper ist mit schrecklichem Giftgas gefuellt. Es verbreitet einen heftigen Gestank, wenn es in der Naehe ist.",
    110: "Pumpt sich eines der zwei Smogon auf, laesst das andere Luft ab. So findet ein Giftgasaustausch statt.",
    111: "Stark, aber nicht allzu klug, kann dieses Pokemon sogar Hochhaeuser mit seinem Tackle-Angriff zum Einsturz bringen.",
    112: "Durch seine panzeraehnliche Koerperhuelle kann es in bis zu 2 000 Grad heisser Lava leben.",
    113: "Man sagt, es bringe Glueck. Es ist sehr mitfuehlend und teilt seine Eier mit Verletzten.",
    114: "Aufgrund der Ranken, die seinen Koerper bedecken, kennt keiner seine wahre Form. Die blauen Ranken wachsen immer weiter.",
    115: "Sein Nachwuchs waechst in seinem Beutel heran. Nur wenn es sicher ist, darf das Junge aus dem Beutel.",
    116: "Dieses Pokemon schiesst mit Tinte auf ueber der Wasseroberflaeche fliegende Insekten.",
    117: "Sein Koerper ist mit scharfen Stacheln gespickt. Wenn man sorglos ist und es beruehrt, kann man durch die Stacheln bewusstlos werden.",
    118: "Es schwimmt mit fuenf Knoten. Wird es angegriffen, wehrt es sich mit seinem scharfen Horn.",
    119: "Im Herbst, zur Paarungszeit, sieht man diese Pokemon kraftvoll Baeche und Fluesse hinaufschwimmen.",
    120: "Auch wenn sein Koerper nicht mehr intakt ist, kann es sich regenerieren, wenn der Kern leuchtet.",
    121: "Der Kern dieses Pokemon leuchtet in den Farben des Regenbogens. Sein Kern gilt als Edelstein.",
    122: "Seine Fingerspitzen sondern etwas ab, das die Luft zu einer schuetzenden Wand werden laesst.",
    123: "Es zerreisst und zerkleinert seine Beute mit seinen unglaublich scharfen Sicheln. Selten breitet es seine Fluegel aus, um zu fliegen.",
    124: "Der beschwingte Gang dieses Pokemon bezaubert Zuschauer und laesst sie im Takt dazu tanzen.",
    125: "Elektrizitaet bedeckt seinen Koerper. Im Dunkeln erstrahlt es in einem blaeulichen Ton.",
    126: "Es wurde in der Naehe eines Vulkans gefunden. Die Koerpertemperatur dieses Feuerspuckers liegt bei fast 1 200 Grad.",
    127: "Es haelt seine Beute mit seiner Zange fest und teilt sie dann. Was es nicht teilen kann, wirft es fort.",
    128: "Es kaempft mit vollem Einsatz, nachdem es sich mit seinen drei Schweifen auspeitschte, um sich anzustacheln.",
    129: "Es ist nutzlos, was Kraft und Geschwindigkeit angeht. Dieses ist das schwaechste und erbaermlichste Pokemon der Welt.",
    130: "In alten Schriften wird von einem Garados berichtet, das in einem Wutanfall ein Dorf zerstoerte.",
    131: "Sie sind gutmuetig. Da sie selten kaempfen, wurden sie oft gefangen. Ihre Anzahl ist stark reduziert.",
    132: "Es kann seine Zellstruktur so veraendern, dass es sich in alles verwandeln kann, was es sieht.",
    133: "Ein seltenes Pokemon, das sich seiner Umgebung anpasst, indem es sich in unterschiedliche Formen entwickelt.",
    134: "Es liebt schoene Ufer. Da seine Zellstruktur Wassermolekuelen aehnlich ist, kann es mit Wasser verschmelzen.",
    135: "Laedt es sich mit Elektrizitaet auf, steht jedes einzelne seiner Koerperhaare steil nach oben.",
    136: "In seinem Koerper befindet sich eine Flamme. Seine Koerpertemperatur liegt vor dem Kampf bei 900 Grad.",
    137: "Ein kuenstlich produziertes Pokemon, welches das Ergebnis von Forschungen ist. Es ist simpel aufgebaut.",
    138: "Ein praehistorisches Pokemon, das zur Urzeit im Wasser lebte. Es schwimmt, indem es seine zehn Tentakel bewegt.",
    139: "Seine Tentakel sind hoch entwickelt und es setzt sie aehnlich Haenden und Fuessen ein. Sobald es Beute ergriffen hat, beisst es zu.",
    140: "Man geht davon aus, dass dieses Pokemon vor 300 Millionen Jahren die Straende bevoelkerte.",
    141: "Im Wasser zieht es seine Beine an und bewegt seinen Panzer, um so schneller schwimmen zu koennen.",
    142: "In Bernstein eingeschlossenes genetisches Material eines Dinosauriers war der Ursprung dieses Pokemon. Beim Fliegen schreit es schrill.",
    143: "Es ist erst satt, wenn es ueber 400 kg Nahrung am Tag gefressen hat. Ist es mit dem Essen fertig, schlaeft es sofort ein.",
    144: "Ein Legendaeres Vogel-Pokemon. Es kann Blizzards verursachen, indem es Feuchtigkeit gefriert.",
    145: "Ein Legendaeres Vogel-Pokemon, das im Sturzflug aus den Wolken bricht und Blitze schleudert.",
    146: "Dieses Pokemon ist der Legendaere Feuervogel. Sein Fluegelschlag entfacht ein helles Feuermeer.",
    147: "Man nennt es \"Illusion-Pokemon\", denn nur wenige haben es gesehen. Nur seine Haut wurde oft gefunden.",
    148: "Die kristallenen Baelle an seinem Schweif ermoeglichen es ihm, das Wetter zu beeinflussen.",
    149: "Trotz seines wuchtigen und massiven Koerpers kann es fliegen. Es umrundet den Erdball in nur 16 Stunden.",
    150: "Dieses Pokemon ist das Resultat eines jahrelangen und skrupellosen Experimentes.",
    151: "Es beherrscht alle moeglichen Attacken, daher sieht man in ihm den Vorfahren aller Pokemon.",
    152: "Ein suesser Duft geht von dem Blatt auf seinem Kopf aus. Es ist ruhig und liegt gerne in der Sonne.",
    153: "Ein wuerziges Aroma geht von seinen Blaettern aus. Das Aroma soll gesundheitsfoerdernd sein.",
    154: "Das Aroma aus seiner Bluete enthaelt Stoffe, die jegliche Aggressivitaet schwinden lassen.",
    155: "Es ist ruhig und kugelt sich stets zusammen. Zum Schutz entflammt es seinen Ruecken.",
    156: "Vor dem Kampf dreht es dem Feind den Ruecken zu, um ihm zu zeigen, wie Furcht erregend sein Feuer lodert.",
    157: "Wenn sein Zorn den Zenit uebersteigt, wird es so heiss, dass alles, was es beruehrt, in Flammen aufgeht.",
    158: "Es ist klein, aber zaeh und stark. Es zoegert nicht, jeden anzugreifen, wenn dieser ihm zu nahe kommt.",
    159: "Verliert es einen seiner Zaehne, waechst ein neuer nach. Es hat immer 48 Zaehne in seinem Kiefer.",
    160: "Eigentlich bewegt es sich langsam, doch seine Beute greift es blitzschnell an.",
    161: "Wenn es Wache hat, warnt es seine Artgenossen, indem es schreit und mit dem Schwanz auf den Boden schlaegt.",
    162: "Es rollt sich um seine Jungen, wenn diese schlafen sollen. Gegnern begegnet es mit Schnelligkeit.",
    163: "Sein Zeitgefuehl ist perfekt. Was auch immer passiert, es behaelt den Rhythmus, da sein Kopf wackelt.",
    164: "Sein Sehvermoegen ist hervorragend. Selbst bei schwachem Licht kann es jedes Detail erkennen.",
    165: "Wird es kalt, versammeln sich viele Ledyba von nah und fern, um sich gegenseitig Waerme zu schenken.",
    166: "Leuchten die Sterne am Nachthimmel, schwirrt es umher und verstreut einen strahlenden, leuchtenden Puder.",
    167: "Es spinnt ein Netz aus feinem, aber reissfestem Faden. Dann wartet es auf Beute, die im Netz zappelt.",
    168: "Da es Faeden sowohl mit dem Hinterleib als auch mit dem Mund spinnt, verwechselt man die beiden leicht.",
    169: "Mit seinen vier Fluegeln fliegt es so geraeuschlos durch die Nacht, dass man es nicht bemerkt.",
    170: "Am Meeresgrund kann es sich nur durch staendiges Flackern seiner Lichter der Umgebung kundtun.",
    171: "Lanturns Licht kann aus grossen Tiefen heraufscheinen. Man nennt es auch \"Tiefseestern\".",
    172: "Sie spielen miteinander, indem sie ihre Schweifspitzen aneinanderhalten und Funken fliegen lassen.",
    173: "Aufgrund seiner ungewoehnlichen Sternform sagt man, es sei auf einem Meteor hierhergereist.",
    174: "Anstatt mit seinen kurzen Beinen zu laufen, huepft es mit seinem weichen und kuscheligen Koerper.",
    175: "Seine Schale ist voll von Freude. Es teilt sein Glueck, wenn man es freundlich und gut behandelt.",
    176: "Es wird entmutigt, wenn es unter unfreundlichen Menschen ist. Es kann ohne Fluegel niedrig schweben.",
    177: "Da seine Fluegel nicht voll ausgebildet sind, bewegt es sich huepfend. Es starrt immer etwas an.",
    178: "Wenn es bei Sonnenaufgang anfaengt zu meditieren, vergeht der ganze Tag, ehe es sich wieder bewegt.",
    179: "Sein weiches Fell wird doppelt so dick, wenn sich Elektrizitaet aufbaut.",
    180: "Sein flauschiges Fell speichert Elektrizitaet. Seine Gummihaut schuetzt es vor Stromstoessen.",
    181: "Seine Schweifspitze ist so hell, dass viele Verschollene es als Orientierungspunkt nutzen.",
    182: "Blubella kommen zusammen, um zu tanzen. Man sagt, dieser Tanz sei ein Ritual, um der Sonne zu huldigen.",
    183: "Sein Fell ist von Natur aus wasserabweisend. Es bleibt trocken, auch wenn es im Wasser spielt.",
    184: "Seine langen Ohren sind hervorragende Sensoren. Mit ihnen kann es Bewegungen im Fluss wahrnehmen.",
    185: "Obwohl es vorgibt, ein Baum zu sein, kommt seine Zusammensetzung einem Stein naeher als einer Pflanze.",
    186: "Sind drei oder mehr von ihnen zusammen, lassen sie einen schallenden Ruf erklingen.",
    187: "Sein Koerper ist so leicht, dass es seine Fuesse im Boden verankert, damit es nicht davongeweht wird.",
    188: "Temperaturschwankungen veranlassen es, die Bluete auf seinem Kopf immer zu oeffnen oder zu schliessen.",
    189: "Es laesst sich von den Winden um den Globus tragen und verteilt auf seinem Flug Baumwollsamen.",
    190: "Es lebt in den Kronen grosser Baeume. Es huepft von Ast zu Ast und balanciert mit seinem Schweif.",
    191: "Manchmal faellt es ploetzlich vom Himmel. Wird es von Habitak angegriffen, schuettelt es seine Blaetter.",
    192: "Steht der Sommer bevor, werden die Blaetter um das Gesicht dieses Pokemon aktiv und lebhaft.",
    193: "Mit seinen Augen hat es einen Blickwinkel von 360 Grad. Es sieht sogar Beute, die sich hinter ihm befindet.",
    194: "Dieses Pokemon lebt in Eiswasser. Wird es an Land kalt, verlaesst es das Wasser und sucht nach Futter.",
    195: "Ein traeges Pokemon, das auf dem Grund des Flusses liegt und wartet, dass ihm Beute ins Maul schwimmt.",
    196: "Die Spitze seines geteilten Schweifs bebt, wenn es die naechste Attacke seines Feindes voraussagt.",
    197: "Mondlicht hat die genetische Struktur von Evoli veraendert. Im Dunkeln wartet es auf Beute.",
    198: "Es versteckt jeden schimmernden Gegenstand. Kramurx und Mauzi rauben sich gegenseitig die Beute.",
    199: "Sein feines Gespuer und Intellekt zeichnen es aus. Es bleibt in jeder Situation gelassen und besonnen.",
    200: "Es naehrt sich von der Angst anderer Wesen und nimmt diese in roten Kugeln auf. Schlaeft am Tage.",
    201: "Sein flacher, duenner Koerper haengt immer an Waenden. Seine Form scheint eine Bedeutung zu haben.",
    202: "Es hasst Licht und Schlaege. Wird es angegriffen, pumpt es sich auf, um einen Gegenschlag vorzubereiten.",
    203: "Waehrend es schlaeft, haelt sein Schweif Wache. Dieser benoetigt keinen Schlaf.",
    204: "Es fuegt seiner Schale schichtenweise Baumrinde hinzu. Die zusaetzliche Belastung ist ihm gleich.",
    205: "Dieses Pokemon ist von einer Stahlhuelle umgeben. Seine stechenden Augen sind alles, was man von ihm sieht.",
    206: "Wird es entdeckt, fluechtet dieses Pokemon, indem es sich mit seinem Schweif in den Boden graebt.",
    207: "Es haengt meist an Klippen. Erspaeht es Beute, spreizt es seine Fluegel und greift diese sofort an.",
    208: "Hoher Druck und hohe Temperaturen haben seinen Koerper haerter als Stahl werden lassen.",
    209: "Es ist von Natur aus verspielt. Es tollt mit vielen Frauen herum, da es ihnen zugeneigt ist.",
    210: "Es ist trotz seines Aeusseren schuechtern. Wird es wuetend, schnappt es mit seinen Faengen zu.",
    211: "Um seine Giftstacheln abzufeuern, muss es seinen Koerper aufpumpen, indem es 10 l trinkt.",
    212: "Dieses Pokemon kann mit seinen staehlernen Scheren jeden harten Gegenstand muehelos zermalmen.",
    213: "In seinem topffoermigen Panzer gelagerte Beeren verwandeln sich im Nu zu einem dickfluessigen Saft.",
    214: "Dieses kraeftige Pokemon rammt sein stolzes Horn unter den Rumpf des Gegners und wirft ihn um.",
    215: "Es ernaehrt sich von Eiern, die es aus Nestern stiehlt. Beute greift es mit seinen scharfen Krallen an.",
    216: "Findet es Honig, leuchtet die Sichel auf seinem Kopf. Es leckt oft seine mit Honig bedeckten Pfoten.",
    217: "Da es alle Gerueche perfekt unterscheiden kann, findet es sogar Nahrung, die tief im Erdreich ist.",
    218: "Es haelt sich staendig bei Vulkanen auf und ist stets kriechend auf der Suche nach warmen Aufenthaltsorten.",
    219: "Aus seinem poroesen Schneckengehaeuse sprudeln Feuerfontaenen, die seinen Koerper durchfluten.",
    220: "Auf Nahrungssuche schnueffelt es am Boden entlang. Es entdeckt dabei manchmal auch heisse Quellen.",
    221: "Trotz kurzer Beine rutscht es auf eisigen Flaechen nicht aus, da seine Hufe ihm genuegend Halt bieten.",
    222: "Es haeutet sich staendig und waechst. Seine Kopfspitze wurde als Schatz der Schoenheit ausgezeichnet.",
    223: "Es ist aeusserst praezise. Es kann mit seinem Wasserschuss Beute erlegen, die 100 m entfernt ist.",
    224: "Es verkriecht sich gerne in Loechern, von wo aus es Gegner mit Tinte beschiesst. Es bevorzugt Felsspalten und Vasen.",
    225: "Im eingerollten Schweif transportiert es Futter, das es mit denen teilt, die sich verlaufen haben.",
    226: "Schwimmt es schnell genug, kann es ueber die Wellen springen und bis zu 100 m durch die Luefte gleiten.",
    227: "Die dornigen Zweige seines Nests bewirken, dass die Fluegel seiner Jungen fest und hart werden.",
    228: "Im Morgengrauen schallt sein ominoeses Geheule ueber das Gebiet, das es fuer sich beansprucht.",
    229: "In alten Zeiten glaubte man, das Heulen dieses Pokemon sei der Ruf des Todes.",
    230: "Man sagt, es hause in Unterwasserhoehlen. Es kann maechtige Strudel generieren, wenn es gaehnt.",
    231: "Als Zeichen seiner Zuneigung stupst es dich mit dem Ruessel, was dich aber buchstaeblich umwerfen koennte.",
    232: "Aufgrund seiner scharfen Stosszaehne und seiner rauen Haut koennte es mit Tackle ein Haus niederreissen.",
    233: "Seine Faehigkeiten wurden verbessert. Es zeigt manchmal sogar Handlungen, die nicht einprogrammiert sind.",
    234: "Starrt man auf sein Geweih, bekommt man das seltsame Gefuehl, in dessen Mitte gezogen zu werden.",
    235: "Sein Revier markiert es mit seinem pinselartigen Schweif. Es kennt mehr als 5 000 Markierungen.",
    236: "Es strotzt vor Energie. Um noch staerker zu werden, kaempft es weiter, auch wenn es verloren hat.",
    237: "Es kaempft, waehrend es sich wie ein Kreisel dreht. Die Zentrifugalkraft verzehnfacht seine Kampfkraft.",
    238: "Die Lippen sind sein empfindlichster Koerperteil. Neue Dinge untersucht es zuerst damit.",
    239: "Es bewegt seine Arme und generiert damit Elektrizitaet. Diese kann es aber nicht speichern.",
    240: "Seine Koerpertemperatur misst 600 Grad. Beim Ein- und Ausatmen springen gluehende Kohlenstuecke aus seinem Mund.",
    241: "Wenn es gerade ein Junges hat, dann enthaelt seine Milch mehr Naehrstoffe als gewoehnlich.",
    242: "Eier, die es legt, stecken voller Froehlichkeit. Schon ein Bissen erzeugt ein breites Laecheln.",
    243: "Die Regenwolken, die es traegt, ermoeglichen es ihm, Gewitter zu erzeugen. Es strotzt vor Blitzen.",
    244: "Dieses Pokemon jagt ueber das Land. Man sagt, in jedem neuen Vulkan wird ein Entei geboren.",
    245: "Es wandert bestaendig in der Welt herum, um verunreinigtes Wasser zu reinigen. Es zieht mit dem Nordwind.",
    246: "Es ernaehrt sich von Erde. Nachdem es einen Berg verspeist hat, schlaeft es ein, um zu wachsen.",
    247: "Sein Koerper ist hart wie Fels. Es laesst mit Hochdruck Gas ab, um wie eine Rakete nach oben zu schiessen.",
    248: "Es besitzt so viel Kraft, dass es mit nur einer Hand die Erde beben lassen und Berge zerbroeckeln kann.",
    249: "Es schlaeft in einem Tiefseegraben. Schwingt es seine Fluegel, entsteht ein Sturm, der 40 Tage dauert.",
    250: "Sein Koerper soll in sieben Farben leuchten. Im Flug zieht es einen Regenbogen hinter sich her.",
    251: "Dieses Pokemon reist durch Zeit und Raum. Baeume und Wiesen wuchern, wenn es in der Naehe ist.",
    252: "Es klettert blitzschnell Waende empor. Mit seinem Schwanz misst es die Luftfeuchtigkeit, um das Wetter am naechsten Tag vorherzusagen.",
    253: "Seine stark entwickelten Oberschenkelmuskeln verleihen ihm aussergewoehnliche Agilitaet und Sprungkraft.",
    254: "Die Blaetter an seinen Armen koennen dicke Baeume faellen. Im Dschungelkampf gibt es kein staerkeres Pokemon.",
    255: "In seinem Bauch ist ein Flammensack, der stets brennt. Umarmt man es, fuehlt es sich warm an.",
    256: "Es kann zehn Tritte pro Sekunde austeilen. Es gibt schrille Schreie von sich, um Gegner einzuschuechtern.",
    257: "Muehelos springt es selbst ueber 30-stoeckige Haeuser. Sein Feuerschlag fuegt dem Gegner Verbrennungen zu.",
    258: "Durch den propellerartigen Einsatz seiner grossen Schwanzflosse schwimmt es schnell durchs Wasser. Trotz seiner kleinen Groesse ist es...",
    259: "Seine kraeftigen Beine geben ihm sicheren Halt. Es graebt sich in Dreck ein, wenn es schlafen will.",
    260: "Schon ein Hieb seiner steinharten Arme schlaegt selbst den staerksten Felsen zu Bruch.",
    261: "Ein beharrliches Pokemon, das seine Beute jagt, bis diese erschoepft ist.",
    262: "Es wird stets die Befehle eines begabten Trainers befolgen. Dieses Verhalten geht darauf zurueck, dass es frueher im Rudel lebte.",
    263: "Es laeuft im Zickzack. Es hat das Talent, Items im Gras, aber auch im Boden, zu finden.",
    264: "Auf gerader Strecke erreicht es muehelos 100 km/h. Nur die Kurven bereiten ihm grosse Schwierigkeiten.",
    265: "Es isst am liebsten Blaetter. Wird es von einem Staralili angegriffen, verteidigt es sich mit Stacheln.",
    266: "Es bindet sich mit Seide an Aeste und trinkt Regenwasser, waehrend es starr auf seine Entwicklung wartet.",
    267: "Die bunten Fluegel sind sein Markenzeichen. Mit seinem Ruessel saugt es suessen Honig aus Blumen.",
    268: "Sein aus weicher Seide bestehender Koerper erhaertet mit der Zeit. Sobald Risse sichtbar sind, steht die Entwicklung kurz bevor.",
    269: "Nachtaktives Pokemon, das vom Licht der Stadt angezogen wird und dort die Blaetter der Baeume frisst.",
    270: "Es sieht aus wie eine Wasserpflanze. Es dient den Pokemon, die nicht schwimmen koennen, als Faehre.",
    271: "Es lebt am Ufer, wo die Sonne scheint. Tagsueber schlaeft es in einem Bett aus Schilf und wird nachts aktiv.",
    272: "Hoert es froehliche Musik, fuellen sich seine Muskeln mit Energie. Es muss dann einfach tanzen.",
    273: "Mit dem Stiel auf seinem Kopf haengt es sich an Aeste. Bei starkem Wind faellt es durchaus einmal herunter.",
    274: "Der Ton seiner Grasfloete beunruhigt die, die ihn hoeren. Es lebt tief in den Waeldern.",
    275: "Dieses Pokemon wurde als Waechter des Waldes gefuerchtet. Es kann die Gedanken des Gegners lesen und praeventiv handeln.",
    276: "Es ist sehr mutig und stellt sich auch starken Gegnern. Es sucht staendig nach warmen Regionen.",
    277: "Wenn seine beiden Schwanzfedern aufrecht stehen, zeigt das, dass es bei bester Gesundheit ist. Es fliegt elegant in den Himmel empor.",
    278: "Es laesst sich vom Wind der Meere treiben, als waere es ein Segelflugzeug.",
    279: "Es taucht seinen grossen Schnabel ins Wasser und faengt so eine Menge Beute.",
    280: "Es erfasst warme Gefuehle von Menschen und Pokemon mit seinen Hoernern und waermt sich daran auf.",
    281: "Die froehliche Stimmung seines Trainers verleiht ihm Energie fuer psychokinetische Kraft. Wenn es gluecklich ist, tanzt und dreht es sich.",
    282: "Erzeugt ein kleines schwarzes Loch mithilfe all seiner Psycho-Kraefte, um seinen Trainer zu schuetzen.",
    283: "Normalerweise leben sie in Teichen, aber nach einem Schauer am Abend kann man sie auch in Pfuetzen in den Staedten finden.",
    284: "Seine Antenne besitzt ein Augenmuster. Seine vier Fluegel erlauben es, in alle Richtungen zu fliegen.",
    285: "Es bevorzugt feuchte Orte. Am Tag sitzt es regungslos im Schatten des Waldes. Von seinem Kopf sondert es einen giftigen Puder ab.",
    286: "Seine kurzen Arme dehnen sich aus, wenn es zuschlaegt. Seine Technik aehnelt der von Profi-Boxern.",
    287: "Allein bei Bummelz' Anblick werden Gegner von Traegheit gepackt und schlummern alsbald ein.",
    288: "Sein Puls ist konstant so hoch, dass sein Blut immer in Wallung ist und es keine Sekunde stillhalten kann.",
    289: "Das faulste Pokemon der Welt. Es bewegt sich nur, wenn alles Essbare in Reichweite verputzt ist.",
    290: "Da es fast sein gesamtes Leben unter der Erde verbracht hat, ist es nahezu blind. Es setzt daher als Augenersatz seine Fuehler ein.",
    291: "Sein Gesang erzeugt unausweichlich Kopfweh. Es bewegt sich so schnell, dass es beinah unsichtbar zu sein scheint.",
    292: "Ein weggeworfener Kaeferpanzer, der zum Leben erwachte. Schaut man hinein, stiehlt es einem die Seele.",
    293: "Normalerweise murmelt es, aber bei Gefahr beginnt es laut zu schreien. Es hoert auf zu schreien, wenn seine Ohrmuscheln bedeckt werden.",
    294: "Es atmet tief ein und nutzt seine Bauchmuskeln, um die Luft in einem gewaltigen Schrei auszustossen.",
    295: "Sein Heulen hoert man in 10 km Entfernung. Es gibt alle Arten von Geraeuschen von sich.",
    296: "Indem es wieder und wieder Baeume rammt, erhaelt es einen zaehen Koerper und einen stahlharten Willen.",
    297: "Es stampft auf den Boden, um Energie zu generieren. Ein einziger Armschlag reicht aus, um einen 10 t schweren LKW durch die Luft zu wirbeln.",
    298: "Dieses Pokemon lebt am Wasser. An Land bewegt es sich schnell, indem es auf seinem grossen Schweif huepft.",
    299: "Es schuetzt sich mit Objekten aus Eisen, die es mithilfe seiner immer nach Norden zeigenden magnetischen Nase anzieht.",
    300: "Es muss Dinge, die sich bewegen, einfach jagen. Es rennt oft im Kreis und jagt seinen eigenen Schweif.",
    301: "Hasst schmutzige Orte. Behagt ihm ein Platz, faengt es sofort an, sein glaenzendes Fell zu pflegen.",
    302: "Es versteckt sich im Dunkeln von Hoehlen. Seine Augen sind Edelsteine.",
    303: "Mit seinem friedlichen Gesicht bringt es Gegner zur Selbstgefaelligkeit und beisst anschliessend mit seinem riesigen Kiefer gnadenlos zu.",
    304: "Normalerweise lebt es in dunklen Bergen. Ist es hungrig, frisst es auch Eisenbahnschienen und Autos.",
    305: "Ist verrueckt nach Eisenerz. Bei Revierkaempfen stossen Stollrak einander mit ihren Stahlkoerpern.",
    306: "Ihre Reviere erstrecken sich ueber ganze Gebirge. Stolloss, die mit Narben uebersaet sind, sollte man besser meiden.",
    307: "Trainiert tief in den Bergen. Erhoeht es seine spirituelle Kraft durch Meditation, kann es schweben.",
    308: "Es weicht Attacken elegant taenzerisch aus, um anschliessend eine verheerende Attacke aus derselben Bewegung heraus zu lancieren.",
    309: "Die Elektrizitaet, die es im Fell speichert, nutzt es, um seine Muskeln zu stimulieren.",
    310: "Es zeigt sich selten den Menschen. Man sagt, dass es sein Nest baut, wo der Blitz eingeschlagen hat.",
    311: "Es feuert Freunde mit Pompons an, die aus Funken bestehen. Es holt sich Energie aus Telegrafenmasten.",
    312: "Mit elektrischen Schlaegen regen Plusle und Minun den Blutkreislauf an und loesen so Verspannungen.",
    313: "Es kommuniziert mit anderen, indem es sein Hinterteil zum Leuchten bringt. Es liebt Illumises Duft.",
    314: "Sein suesser Duft leitet Volbeat an, ueber 200 verschiedene Lichtmuster an den Nachthimmel zu malen.",
    315: "Aus seinen Haenden verstroemt es jeweils ein anderes Gift. Je staerker Roselia duftet, desto gesuender ist es.",
    316: "Sein Koerper besteht fast nur aus Magen. Herz und Hirn sind winzig. Sein Magensaft verdaut alles.",
    317: "Es verschluckt alles in einem Stueck und sondert giftige Stoffe ab, mit denen es Gegner besprueht.",
    318: "Schwaerme von Kanivanha haben in Dschungelfluessen schon so manches Boot zerbissen und versenkt.",
    319: "Seine Zaehne durchdringen sogar Eisen. Es schwimmt mit 120 km/h und wird \"Tyrann des Meeres\" genannt.",
    320: "Es huepft gerne wie ein Ball herum. Je mehr Meerwasser es trinkt, desto hoeher kann es springen.",
    321: "Springt es mit seinem gewaltigen Koerper von einer Welle ab, kann es Gegner allein mit der Wucht des Aufpralls besiegen.",
    322: "In seinem Ruecken speichert es sehr heisses Magma. Regnet es, kuehlt das Magma ab und es wird langsamer.",
    323: "Seine Vulkanhoecker brechen nur alle zehn Jahre aus oder wenn es richtig wuetend ist.",
    324: "Grosse Gruppen Qurtel siedeln sich in stillgelegten Bergwerken an und graben dort emsig nach Kohle.",
    325: "Es huepft bestaendig umher, wobei es seinen Schweif als Feder verwendet. Nur so bleibt sein Herz aktiv.",
    326: "Mit schwarzen Perlen verstaerkt es seine Psycho-Kraefte. Mit einem Tanz kontrolliert es seine Gegner.",
    327: "Das Muster eines Pandir ist wie ein Fingerabdruck. Sein Taumeln senkt die gegnerische Zielsicherheit.",
    328: "Es lebt in trockenen Wuestengebieten, wo es eine Trichterfalle baut und seelenruhig darauf wartet, dass Beute hinabrutscht.",
    329: "Die Schallwellen, die es durch eine hohe Fluegelschlagfrequenz erzeugt, verursachen heftige Kopfschmerzen.",
    330: "Es versteckt sich, indem es mit seinen Fluegeln Wuestensand aufwirbelt. Rote Augenlider schuetzen es vor dem Sand.",
    331: "Es waechst an trockenen Orten mit wenig Niederschlag. Nur einmal im Jahr bildet es eine gelbe Bluete.",
    332: "Ein nachtaktives Pokemon, das Beute sucht, die durch die Tageshitze der Wueste bereits erschoepft ist.",
    333: "Aus irgendeinem Grund setzt es sich gerne auf den Kopf von Menschen und tut so, als sei es ein Hut.",
    334: "Es schwebt gemaechlich durch den Himmel. Sein wunderschoenes Summen gibt einem das Gefuehl zu traeumen.",
    335: "Seit Generationen ist es mit Vipitis verfeindet. Seine scharfen Klauen sind seine staerksten Waffen.",
    336: "Die flinken Angriffe von Sengo kontert es mit seinem messerscharfen Schweif, aus dem Gift austritt.",
    337: "Da es in Vollmondnaechten aktiv wird, sagt man ihm nach, mit den Mondphasen in Verbindung zu stehen.",
    338: "Da es seine Energie aus Sonnenlicht gewinnt, ist es tagsueber am staerksten. Wenn es sich dreht, leuchtet es.",
    339: "Es bedeckt seinen Koerper mit einer schleimigen Substanz und kann sich so aus Umklammerungen winden.",
    340: "Sein Revier hat es im Sumpfland. Naehert sich ein Feind, zappelt es wie wild und erzeugt so Erdbeben.",
    341: "Egal, wie schmutzig der Fluss ist, in dem sie leben, sie passen sich daran an und vermehren sich. Sie sind hart im Nehmen.",
    342: "Dieser Grobian ergreift andere Pokemon mit seinen Scheren und wirft sie aus seinem Teich.",
    343: "Es bewegt sich, indem es auf seinem Fuss kreiselt. Vereinzelt sieht man Puppance, die kopfueber kreiseln.",
    344: "Eine antike Lehmstatue, die durch ein mysterioeses Licht zum Leben erwacht ist.",
    345: "Vor 100 Millionen Jahren starb es aus. Es faengt seine Beute mit als Bluete getarnten Tentakeln.",
    346: "Es lebt in seichten Stellen warmer Meere. Bei Ebbe sucht es im Sand nach Beute.",
    347: "Es ist eine Art Vorfahre der Pokemon. Mit seinen erweiterten Scheren geht es zwischen den Felsen am Meeresgrund auf Beutefang.",
    348: "Es spiesst die Beute mit seinen Scheren auf, ehe es sie verspeist. Den Koerper umgibt ein robuster Panzer.",
    349: "Es frisst einfach alles und kann daher auch in verschmutzter Umgebung leben. Niemand beachtet es.",
    350: "Milotic ist atemberaubend schoen. Man sagt, dass diejenigen, die es sehen, vergessen zu kaempfen.",
    351: "Formeo kann seine Gestalt aendern. Seine Zellen reagieren auf Temperaturschwankungen und Feuchtigkeit.",
    352: "Es kann nach Belieben seine Farbe aendern. Nur das gezackte Muster auf seinem Bauch bleibt gleich.",
    353: "Man sagt, durch sein Horn ernaehre es sich von Rachsucht und Neid. Erst nachts wird es richtig aktiv.",
    354: "Dieses Pokemon war eine Puppe, die weggeworfen wurde. Es sucht nun das Kind, das dies getan hat.",
    355: "Verbissen verfolgt es seine Beute ueberallhin. Doch sobald die Sonne aufgeht, ist die Jagd vorbei.",
    356: "Blickt man direkt in den Feuerball in seinem Inneren, wird einem die Seele ausgesaugt.",
    357: "Es nutzt seine grossen Blaetter als Fluegel und verteilt die suessen Fruechte, die an seinem Hals wachsen, an Kinder.",
    358: "Mit seinem Saugnapf haengt es sich an Aeste oder unter Vordaecher. Es kennt sieben verschiedene Schreie.",
    359: "Es spuert drohende Katastrophen und erscheint nur dann, wenn es andere vor der Gefahr warnen will.",
    360: "Es zieht normalerweise im Rudel umher. Zum Schlafen draengen sie sich ganz eng in einer Hoehle zusammen.",
    361: "Geruechten zufolge sammeln sich Schneppke unter riesigen Blaettern und leben dort friedlich zusammen.",
    362: "Um sich zu schuetzen, umgibt es seinen Koerper mit einer Ruestung aus Eis.",
    363: "Es ist noch kein guter Schwimmer und bewegt sich rollend schneller fort. Ist es froh, klatscht es mit seinen Flossen.",
    364: "Die Nerven in seiner Nase sind sehr empfindlich. Sieht es etwas Neues, beruehrt es es zuerst mit der Nase.",
    365: "Mit seinen Stosszaehnen bricht es durch Eis. Eine Speckschicht schuetzt es vor Kaelte und Angriffen.",
    366: "Es entwickelt sich nur einmal im Leben, wobei es eine wundersame Perle erzeugt, die Psycho-Kraefte verstaerkt.",
    367: "Es lebt tief im Meer, wo Sonnenlicht nie vordringt. Beim Beutefang leuchtet sein fischartiger Schwanz, um Beute anzulocken.",
    368: "Es lebt auf dem Grund des Meeres. Im Fruehling wirkt die Farbe seines Koerpers viel kraeftiger.",
    369: "100 Millionen Jahre lang blieb es unveraendert. Es wurde bei einer Tiefsee-Tauchexpedition entdeckt.",
    370: "Es lebt in warmen Meeren. Man sagt, dass Verliebte, die es sehen, mit ewiger Liebe gesegnet sind.",
    371: "Mit seinen robusten Nackenmuskeln und seinem stahlharten Kopf kann es sogar Felsen zertruemmern.",
    372: "Die Zellen seines Panzers fingen an, sich zu veraendern. Er faellt ab, sobald sich das Pokemon entwickelt.",
    373: "Wenn es wuetend ist, geraet es ausser Kontrolle. Es zerstoert alles mit seinen Klauen und mit Feuer.",
    374: "Es fliegt, indem es eine magnetische Kraft erzeugt, durch die es der natuerlichen Anziehungskraft der Erde trotzt.",
    375: "Das Pokemon besteht aus zwei Tanhel. Es bekommt selbst dann keinen Kratzer, wenn ein Jet es streift.",
    376: "Dank seiner vier vernetzten Hirne kann es Gegner besser als ein Supercomputer mit komplizierten Formeln analysieren.",
    377: "Sein Koerper besteht aus Stein. Bricht im Kampf etwas heraus, wird es durch Stein wieder ersetzt.",
    378: "Es heisst, es habe Jahrtausende lang im ewigen Eis geschlummert. Selbst Magma schmilzt es nicht.",
    379: "Im Laufe der Jahrtausende, die es unterirdisch lebte, wurde sein Koerper durch Druck und Waerme hart.",
    380: "Es kommuniziert durch Telepathie. Sein Daunenkleid bricht das Licht, sodass es unsichtbar wird.",
    381: "Ein hochintelligentes Pokemon. Wenn es im Flug seine Fluegel nach hinten legt, ist es schneller als ein Jet.",
    382: "Der Legende nach erschuf sein Regen das Meer. Es und Groudon lieferten sich einen langen Kampf.",
    383: "Sein Feuer erschuf einst das Land. Es und Kyogre lieferten sich einen langen Kampf.",
    384: "Es lebt in der Ozonschicht hoch ueber den Wolken und kann vom Boden aus nicht gesehen werden.",
    385: "Wenn Jirachi erwacht, erfuellt es die Wuensche, die man auf die Zettel an seinem Kopf geschrieben hat.",
    386: "Ein ausserirdischer Virus kam mit einem Meteor auf die Erde. Seine DNA mutierte. So entstand Deoxys.",
    387: "Im Sonnenlicht betreibt sein ganzer Koerper Photosynthese. Sein Panzer besteht aus hartem Lehm.",
    388: "Es lebt in der Naehe von Wasser in Waeldern. Tagsueber verlaesst es diese, um ein Sonnenbad zu nehmen.",
    389: "In alten Zeiten malten die Menschen sich aus, die Erde ruhe auf dem Ruecken eines riesigen Chelterrar.",
    390: "Das Feuer an seinem Hinterteil wird durch Gase im Bauch genaehrt. Selbst Regen loescht es nicht.",
    391: "Es kontrolliert die Staerke des Feuers auf seinem Schweif geschickt, um Gegner auf Distanz zu halten.",
    392: "Seine Krone aus Feuer ist Zeichen seines feurigen Wesens. Niemand ist schneller im Kampf als dieses Pokemon.",
    393: "Einmischung kann es gar nicht leiden. Es ist bockig und fasst nur schwer Zutrauen zu seinem Trainer.",
    394: "Es lebt allein, entfernt von anderen. Jedes von ihnen denkt, es sei das Bedeutendste unter ihnen.",
    395: "Es schwimmt so schnell wie ein Rennboot. Seine Fluegel haben scharfe Seiten und koennen Packeis schneiden.",
    396: "Ihr Schwarm ist stets gross. Obwohl es kleine Pokemon sind, schwingen sie ihre Fluegel mit enormer Kraft.",
    397: "Es neigt dazu, sich in grossen Gruppen zu bewegen. Zwischen ihnen kommt es zu heftigen Kaempfen.",
    398: "Die Muskeln in seinen Fluegeln und Beinen sind stark. Es kann im Flug sogar ein anderes Pokemon tragen.",
    399: "Es hat Nerven wie Drahtseile, nichts kann es erschuettern. Es ist agiler und aktiver, als es scheint.",
    400: "Emsig durchbeisst es mit seinen scharfen Vorderzaehnen Wurzeln und Aeste und baut daraus sein Nest.",
    401: "Diese Pokemon unterhalten sich, indem sie ihre Antennen aneinanderschlagen. Der Ton ist ihr Kennzeichen.",
    402: "Wenn es ruft, verschraenkt es seine messerartigen Arme vor der Brust. Es komponiert aus dem Stegreif.",
    403: "Es erzeugt Elektrizitaet durch das Strecken und Zusammenziehen seiner Muskeln. Bei Bedrohung glueht es.",
    404: "Seine Krallen geben Elektrizitaet ab, die stark genug ist, jemanden bewusstlos zu machen.",
    405: "Leuchten seine Augen golden auf, kann es Beute, die sich versteckt, sehen. Es kann durch Waende sehen.",
    406: "Bei Sonnenlicht oeffnet es seine Knospe und gibt Pollen ab. Es lebt in der Naehe von sauberem Wasser.",
    407: "Es lockt seine Beute mit suessem Duft an, um sie danach mit seinen dornigen Ranken zu peitschen oder zu wuergen.",
    408: "Es wurde aus einem ballartigen, eisernen Fossil geschaffen. Es schlaegt Beute mit einem Kopfstoss.",
    409: "Sein dicker Schaedelknochen trotzt jedem Angriff. Gleichzeitig stoppt er jedoch sein Hirnwachstum.",
    410: "Es reibt sein Gesicht an Baumstaemmen, um es zu polieren. Es ist leicht, es von hinten anzugreifen.",
    411: "Stellen sie sich Seite an Seite, kann kein Gegner hindurchbrechen. So schuetzen sie auch ihre Jungen.",
    412: "Um sich vor dem eisigen Winterwind zu schuetzen, legt es sich unter einen Umhang aus Aesten und Laub.",
    413: "Die Umgebung, in der es sich entwickelt, bestimmt sein Aussehen. Es formt seinen Koerper mithilfe der umliegenden Materialien.",
    414: "Es liebt Honig und stiehlt den Honig, der von Wadribie gesammelt wurde.",
    415: "Dieses Trio ist von Geburt an zusammen. Fleissig bringt es Bluetenhonig zu Honweisel.",
    416: "Es beherbergt Jung-Pokemon in seinem Rumpf, die es mithilfe von verschiedenen Pheromonen frei herumkommandieren kann.",
    417: "Es bildet ein Fellknaeuel, der vor statischer Energie knistert. Es speichert die Energie in Baeumen.",
    418: "Es schwimmt, indem es seine beiden Schweife wie eine Schiffsschraube rotieren laesst.",
    419: "Es treibt mithilfe einer Art Rettungsring auf dem Wasser und hilft dem, der zu ertrinken droht.",
    420: "Sonnenlicht faerbt es rot. Verliert das kleine Baellchen Naehrstoffe, welkt es und die Entwicklung beginnt.",
    421: "Bei Sonnenschein entfaltet seine Knospe ihre Bluetenblaetter und es springt lebhaft umher.",
    422: "Nicht seinen Koerper zusammendruecken, sonst sickert eine seltsame lilafarbene Fluessigkeit aus!",
    423: "Wird es von einem natuerlichen Feind angegriffen, flieht es, indem es ein lila Sekret ueber die Haut ausstoesst.",
    424: "Sie leben in grossen Kolonien und verbinden ihre Schweife in Freundschaft.",
    425: "Ein Pokemon, entstanden aus den Gefuehlen von Menschen und Pokemon. Es mag feuchte Jahreszeiten.",
    426: "Es traegt Menschen und Pokemon im Flug. Da es sich aber nur vom Wind tragen laesst, weiss man nie, wo es hingeht.",
    427: "Seine Ohren sind immer aufgerollt. Mit ihnen kann es selbst grosse Felsbrocken zertruemmern.",
    428: "Es ist extrem vorsichtig. Wenn es Gefahr wittert, macht es sich mit flinken Spruengen aus dem Staub.",
    429: "Es spricht Beschwoerungen. Viele loesen Schmerzen aus, manche aber bringen Glueck.",
    430: "Sein tiefer Ruf lockt andere Kramurx herbei. Man nennt es daher \"Beschwoerer der Nacht\".",
    431: "Es schlaegt mit Krallen zu oder schnurrt, je nachdem, ob es gerade wuetend oder zutraulich ist.",
    432: "Behagt ihm die Behausung eines anderen Pokemon, bleibt Shnurgarst einfach da und nistet sich dort ein.",
    433: "Jedes Mal, wenn es huepft, entsteht ein klingender Laut. Seine hohen Schreie machen die Gegner taub.",
    434: "Versprueht eine Substanz aus seinem Hinterleib, die in einem grossen Radius andere Pokemon fernhaelt.",
    435: "Ueber seine Schweifspitze versprueht es eine uebelriechende Substanz. Die Reichweite liegt bei ueber 50 m.",
    436: "Frueher glaubten die Menschen, dem Muster auf seinem Ruecken wohne eine mysterioese Kraft inne.",
    437: "Man verehrt sie schon seit Urzeiten als Regenmacher. Manchmal findet man eines von ihnen im Boden vergraben.",
    438: "Es bevorzugt trockene Gebiete. Es gibt ueber die Augen Wasser ab, um den Wasserhaushalt zu regulieren.",
    439: "Es ahmt seinen Gegner nach. Waehrend dieser noch verbluefft dreinsieht, macht es sich aus dem Staub.",
    440: "In seinem Beutel traegt es einen runden, eifoermigen Stein, den es Freunden gibt.",
    441: "Es versucht Attacken zu entgehen, indem es den Ruf des Gegners nachahmt und einen Artgenossen mimt.",
    442: "Ein Pokemon, das aus 108 Geistern besteht. Es ist an einen Spalt in einem mysterioesen Stein gebunden.",
    443: "Es lebt in Hoehlen, die Erdwaerme ausgesetzt sind. Es springt heraus und beisst, wenn Feinde sich naehern.",
    444: "Es liebt funkelnde Dinge und sucht nach Schaetzen in Hoehlen, die es dann in seinem Nest hortet.",
    445: "Spannt es seinen Koerper und seine Fluegel, sieht es aus wie ein Jet. Es fliegt mit Schallgeschwindigkeit.",
    446: "Unter seinem langen Fell versteckt es Nahrung. Aber es vergisst, dass es sie dort versteckt hat.",
    447: "Es kommuniziert mit seinen Artgenossen ueber Wellen, die je nach Gefuehlslage eine andere Form annehmen.",
    448: "Es nimmt die Aura seines Gegners wahr. So kann es dessen Gedanken und Bewegungen erkennen.",
    449: "Es lebt in ausgetrockneten Gebieten. Statt zu schwitzen, sondert sein Koerper Sand ab.",
    450: "Das weit aufgerissene Maul demonstriert seine Staerke. Es attackiert mit gebuendeltem Sand.",
    451: "Es greift seine Beute mit den Krallen an seinem Schweif und vergiftet sie. Dann wartet es ab...",
    452: "Es bringt seine Gegner mit starkem Gift zur Strecke, obwohl es weiss, dass es stark genug ist, um sie zu zerfetzen.",
    453: "In seinen Backen sammelt sich Gift. Es versucht, Beute zu ueberraschen und mit Giftfingern zu schnappen.",
    454: "Verfuegt ueber einen Giftsack an seiner Kehle. Quakt es, schaeumt das Gift und wird so noch staerker.",
    455: "Sein suesslich riechender Speichel zieht Beute an, die es frisst. Es braucht einen Tag, sie zu fressen.",
    456: "Die Linie an seiner Seite kann Sonnenlicht speichern. Nachts leuchtet es sehr intensiv.",
    457: "Es lebt tief auf dem Meeresboden. Das blinkende Muster auf seinen vier Rueckenflossen zieht Beute an.",
    458: "Ihre Ruecken sind je nach Region unterschiedlich gemustert. Oft mischen sie sich unter Remoraid-Schwaerme.",
    459: "Im Winter steigt es bis zum Fuss der Berge herab. Im Fruehjahr kehrt es auf den Gipfel zurueck.",
    460: "Es bedeckt weite Gebiete mit Schnee, indem es Blizzards ausloest. Man nennt es \"Das Eismonster\".",
    461: "Es lebt in schneereichen Gebieten. Snibunna senden einander Signale, indem sie Zeichen in Rinde ritzen.",
    462: "Gelegentlich erzeugen sie so starke Magnetfelder, dass sie sich gegenseitig anziehen und einander immobilisieren.",
    463: "Es umklammert Dinge mit seiner dehnbaren Zunge. Kommt man ihm zu nahe, wird man eingespeichelt.",
    464: "Es feuert Kleinstein aus seinen Handflaechen. Durch seinen Schuetzer ertraegt es sogar Vulkanausbrueche.",
    465: "Es umwickelt Beute, indem es seine Arme, die aus Ranken bestehen, verlaengert.",
    466: "Bei voller Ladung zucken feurige, blassweisse Funken zwischen seinen zwei Hoernern hin und her.",
    467: "Aus den Enden seiner Arme schiessen Feuerbaelle mit 2 000 Grad. Es lebt in Vulkankratern.",
    468: "Es heisst, Togekiss erscheine in friedlichen Zeiten und verteile alle moeglichen Wohltaten.",
    469: "Seine bevorzugte Strategie besteht darin, seine Gegner aus dem Flug blitzartig zur Strecke zu bringen.",
    470: "An klaren Tagen erzeugt Folipurba saubere Luft, indem es Photosynthese betreibt.",
    471: "Erzeugt ein Diamantstaubgestoeber durch das Einfrieren der Luft um sich herum.",
    472: "Es haengt kopfueber von einem Ast und beobachtet seine Beute. Bei Gelegenheit stuerzt es sich auf sie.",
    473: "Es existiert schon seit Urzeiten. Mamutel wurde sogar schon in 10 000 Jahre altem Eis gefunden.",
    474: "Zusaetzliche Software wurde installiert, um das Pokemon zu verbessern. Seitdem benimmt es sich seltsam.",
    475: "Da es selbst die leisesten Gedanken seines Gegners lesen kann, kann es immer zuerst angreifen.",
    476: "Es gibt starken Magnetismus ab. Es steuert drei kleine Einheiten, die sich Mininasen nennen.",
    477: "Man sagt, dass es verlorene Seelen in seinem biegsamen Koerper nach Hause geleite.",
    478: "Sein eisiger Atem mit -50 Grad friert Gegner ein. Was aussieht wie sein Koerper, ist tatsaechlich hohl.",
    479: "Dieses Pokemon wurde lange Zeit erforscht, um als Energiequelle fuer einen besonderen Motor zu dienen.",
    480: "\"Das wissende Wesen\". Es soll die Erinnerungen derer loeschen, die ihm in die Augen sehen.",
    481: "\"Das fuehlende Wesen\". Es lehrt die Menschen die Ideale von Trauer, Schmerz und Freude.",
    482: "\"Das starke Wesen\". Es schlaeft auf dem Grund eines Sees und haelt so die Welt in Balance.",
    483: "Ein Pokemon, das in Legenden zu finden ist. Man sagt, als Dialga geboren wurde, begann der Lauf der Zeit.",
    484: "Man sagt, es lebe in einem Spalt in einer Paralleldimension. Es wird in der Mythologie erwaehnt.",
    485: "Es lebt in vulkanischen Hoehlen. Mit seinen kreuzfoermigen Klauen kann es sogar an der Decke laufen.",
    486: "Man sagt, es habe Pokemon aus einem Eisberg, Felsen und Magma nach seinem Abbild geschaffen.",
    487: "Es lebt in einer Zerrwelt, die auf der Kehrseite der unseren liegt und die sich aller Logik entzieht.",
    488: "Seine Fluegel geben schimmernde Partikel ab, die wie ein Schleier herabrieseln. Man sagt, es verkoerpere die Mondsichel.",
    489: "Steigt die Meerestemperatur, blaest es seinen Schwimmbeutel auf und treibt in Schwaermen auf dem Wasser.",
    490: "Es wird mit einer wundersamen Kraft geboren, die eine Bindung zu jedem anderen Pokemon moeglich macht.",
    491: "Es vertreibt Eindringlinge aus seinem Revier, indem es sie in Schlaf versetzt und mit Alptraeumen quaelt.",
    492: "Es kann die Luft von Giften reinigen und Oedland in ein ueppig bluehendes Blumenfeld verwandeln.",
    493: "In den Legenden Sinnohs heisst es, es sei aus einem Ei geschluepft und haette die gesamte Welt geschaffen.",
    494: "Ein siegverheissendes Pokemon. Man sagt, Trainer, die ein Victini in ihrem Team haben, seien unschlagbar.",
    495: "Im Sonnenlicht erhoeht sich das Tempo seiner Bewegungen. Es ist mit seinen Schlingen geschickter als mit den Haenden.",
    496: "Huscht beinahe gleitend ueber den Boden und taeuscht Gegner mit agilen Manoevern, bis es mithilfe seiner Efeurute obsiegt.",
    497: "Im Kampf zeigt es nur Gegnern, die seinem edlen Blick standhalten, seine wahre Kraft.",
    498: "Weicht flink gegnerischen Angriffen aus und schiesst Flammen aus dem Ruessel, mit denen es gern auch mal Nuesse roestet.",
    499: "Je mehr es frisst, desto staerker werden die Flammen in seinem Magen. Dies fuehrt zu rapiden Energieschueben.",
    500: "Steckt mit dem Feuer um sein Kinn seine Faeuste in Brand und holt zu feurigen Fausthieben aus. Zeigt grossen Teamgeist.",
    501: "Die Muschel an seinem Bauch dient ihm nicht nur als Waffe, sondern auch als Messer, mit dem es Beeren aufschneidet.",
    502: "Es eignet sich durch strenges Training elegant ineinander uebergehende Attacken mit seinen zwei Muscheln an.",
    503: "Ehe man sichs versieht, hat es schon das Langschwert aus seinen Vorderbeinen gezogen und seinen Gegner besiegt.",
    504: "Hortet in seinen Backentaschen Futter, um tagelang Wache stehen zu koennen, und gibt Kameraden ueber seine Rute Signale.",
    505: "Es kann mit einer koerpereigenen Substanz seine Augen und seinen Torso aufleuchten lassen, um Gegner zu erschrecken.",
    506: "Das lange Fell um sein Gesicht fungiert als Hightech-Radar, mit dem es fein saeuberlich seine Umgebung abtastet.",
    507: "Dieses aeusserst treue Pokemon geht nicht nur seinem Trainer zur Hand, sondern hilft auch anderen Pokemon.",
    508: "Es rettet Menschen, die aufgrund eines Schneesturmes im Gebirge festsitzen. Sein langes Fell schuetzt es vor Kaelte.",
    509: "Es lenkt die Menschen durch sein suesses Verhalten ab, um sie zu bestehlen. Ist es wuetend, kratzt es gern mal.",
    510: "Sein anmutiges Auftreten verdankt es den Muskeln, die es entwickelt hat. Es prescht lautlos durch die Nacht.",
    511: "Schwaechelnden Pokemon gibt es ein paar der Kraeuter auf seinem Kopf ab und hilft ihnen so wieder auf die Beine.",
    512: "Wer sich mit diesem temperamentvollen Pokemon anlegt, bekommt seinen mit Dornen bestueckten Schweif zu spueren.",
    513: "Ein kultiviertes Pokemon, das Beeren vor dem Verzehr stets anbraet. Es bietet den Menschen gerne seine Hilfe an.",
    514: "Es entfacht in seinem Koerper ein Feuer und verkohlt Gegner mit Funken aus seinem Kopf und Schweif.",
    515: "Das Bueschel auf seinem Kopf enthaelt eine sehr nahrhafte Fluessigkeit, mit der es ueber seinen Schweif Pflanzen waessert.",
    516: "Es schiesst mit so hohem Druck Wasser aus seinem Schweif, dass selbst Betonwaende den Kuerzeren ziehen.",
    517: "Es erscheint vor schlafenden Menschen und Pokemon und frisst ihre Alptraeume.",
    518: "Der Dunst, der aus seiner Stirn tritt, enthaelt die Traeume unzaehliger Menschen und Pokemon.",
    519: "Wartet oft vergeblich auf Anweisungen, obwohl es bereits einen Befehl erhalten hat. Ein sehr zerstreutes Pokemon.",
    520: "Viele Leute glauben, dass es tief in seinem heimatlichen Wald ein Land der Harmonie gibt, wo man keine Kriege kennt.",
    521: "Maennchen schrecken Gegner ab, indem sie ihren Kopfschmuck schuetteln. Weibchen verfuegen ueber bessere Flugfertigkeiten.",
    522: "Es erscheint, wenn Gewitterwolken den Himmel verdunkeln. Es faengt mit seiner Maehne Blitze und hortet ihre Energie.",
    523: "Ein stuermischer Geselle. Wenn es wuetend ist, feuert es ueber seine Maehne in alle Richtungen Stromsalven ab.",
    524: "Hat ein sechseckiges Ohr. Sein durch das Erdreich gepresster Koerper steht Stahl in Sachen Haerte in nichts nach.",
    525: "Energie, die ungehindert aus seinem Koerper austrat, hat sich an ihm zu orangefarbenen Kristallen verfestigt.",
    526: "Es verarbeitet Sonnenstrahlen in seinem Energiekern zu Lichtkugeln weiter, um sie im Kampf auf seinen Gegner abzufeuern.",
    527: "Wohnt in dunklen Waeldern und Hoehlen. Es sendet Ultraschallwellen mit seiner Nase aus, um die Gegend abzutasten.",
    528: "Beim Abfeuern seiner Ultraschallwellen, mit denen es selbst Beton zertruemmern kann, wedelt es eifrig mit dem Schweif.",
    529: "Es fuehrt seine beiden Klauen zusammen, dreht sich rapide um die eigene Achse und graebt sich ratzfatz durch das Erdreich.",
    530: "Seine zu Stahl weiterentwickelten Bohrer kriegen selbst Eisenplatten klein. Im Tunnelbau ist es ein absolutes Ass.",
    531: "Ueber die Fuehler an seinen Ohren kann es ertasten, wie es einer Person geht oder wann ein Pokemon aus seinem Ei schluepft.",
    532: "Traegt stets einen Holzbalken bei sich. Es taucht hier und da auf Baustellen auf und hilft dort den Arbeitern aus.",
    533: "Diese durchtrainierten Muskelprotze sind im Umgang mit Stahltraegern versiert und koennen damit ganze Haeuser abreissen.",
    534: "Man nimmt an, dass es der Menschheit vor ca. 2 000 Jahren das Betonmischen beigebracht hat.",
    535: "Erzeugt mit seinen Wangen fuer Menschen unhoerbare Schallwellen, um Artgenossen vor Gefahr zu warnen.",
    536: "Wenn es die Beulen auf seinem Kopf zum Schwingen bringt, tobt je nach Umgebung entweder das Wasser oder die Erde bebt.",
    537: "Wenn es die Beulen an seinen Faeusten zum Schwingen bringt, kann es doppelt so fest zuschlagen und Felsen zertruemmern.",
    538: "Zurrt es seinen Guertel fest, gewinnt es an Kraft. Wilde Exemplare flechten sich ihren Guertel in Handarbeit aus Ranken.",
    539: "Es lebt zurueckgezogen in den Bergen und trainiert Tag und Nacht, um seinen Karateschlag zu perfektionieren.",
    540: "Schneidert sich ein Kleid, indem es sich Blaetter zurechtbeisst und sie mit Klebefaeden aus seinem Mund zusammennaeht.",
    541: "Es wandelt herabgefallenes Laub in Naehrstoffe um. In Waeldern, wo es Folikon gibt, fuehlen sich Pflanzen pudelwohl.",
    542: "Begegnet es einem jungen Pokemon, naeht es ihm mit den klebrigen Faeden aus seinem Mund ein Kleid aus Blaettern.",
    543: "Mit seinen Ruten und den Fuehlern an seinem Kopf tastet es die Umgebung ab. Ein ueberaus aggressiver Geselle.",
    544: "Von einem harten Schutzpanzer umgeben. Es greift seine Gegner an, indem es mit Karacho wie ein Rad in sie hineinrollt.",
    545: "Laehmt seine Beute, indem es sie mit den Zacken an seinem Hals aufspiesst. Mit einer Ladung Gift gibt es ihr den Rest.",
    546: "Wird es angegriffen, verstreut es zur Taeuschung Watte. Es flieht, waehrend der Gegner nach dem wahren Waumboll sucht.",
    547: "Sie erscheinen mit Orkanboeen und spielen den Leuten Streiche, indem sie in Haeusern Moebel verruecken oder Watte verstreuen.",
    548: "Die Blaetter auf seinem Kopf schmecken furchtbar bitter, doch sie helfen ausgezeichnet gegen Erschoepfung.",
    549: "Der Duft des Blumenschmucks auf seinem Kopf wirkt beruhigend. Damit der Schmuck nicht verwelkt, muss man es gut pflegen.",
    550: "Sie gelten als Delikatesse. Aufgrund ihrer brutalen Natur liegen rot und blau gestreifte Exemplare immer im Clinch.",
    551: "Wenn es sich durch den Sand graebt, ragen nur noch Nase und Augen hervor. Die schwarze Haut dient als Augenschutz.",
    552: "Bildet mit mehreren Artgenossen ein Rudel. Eine Membran schuetzt seine Augen vor Sandstuermen.",
    553: "Ein aeusserst grausames Pokemon. Es greift jeden, der ihm unter die Augen kommt, mit seinen scharfen Reisszaehnen an.",
    554: "Frueher nutzte man die heissen Ausscheidungen von Flampion, um sich den Koerper zu waermen.",
    555: "Nimmt es in einem heissen Kampf Schaden, wird es hart wie Stein und faellt in eine Trance, um seinen Verstand zu schaerfen.",
    556: "Verjagt Vogel-Pokemon, die auf seine Blueten aus sind, mit einem flotten Taenzchen und lauter Untermalung.",
    557: "Hoehlt sich einen brauchbaren Stein aus, um darin zu wohnen. Geht er zu Bruch, ruht es nicht, bis es einen neuen findet.",
    558: "Es ist hart genug im Nehmen, um mitsamt seines schweren Felsens mehrere Tage durch trockene Gebiete zu wandern.",
    559: "Es zieht seine gummiartige Haut bis zum Hals hinauf und nimmt eine Abwehrhaltung ein, um sich vor Schaden zu schuetzen.",
    560: "Es wehrt Angriffe mit seiner alten Haut ab und kontert mit Tritten. Sein Ego entspricht der Groesse seines Kamms.",
    561: "Einst war es der Waechter einer Stadt aus uralten Zeiten. Wer sich in sein Revier wagt, lernt seine Psycho-Kraefte kennen.",
    562: "Es entsteht aus den Seelen von laengst begrabenen Menschen und kann sich immer noch an deren Vergangenheit erinnern.",
    563: "Angeblich verschlingt es jeden, der sich ihm auch nur naehert. Besonders gern frisst es Klumpen aus reinem Gold.",
    564: "Schwamm bereits vor 100 Millionen Jahren durch die Meere. Ab und zu fuehrt es die Jagd auch an Land.",
    565: "Es lebt im Meer und an Land. Es ist so stark, dass es mit einem einzigen Hieb ein Loch in ein Schiff reissen kann.",
    566: "Es wurde aus einem Fossil reanimiert. Man geht davon aus, dass es der Urahn aller Vogel-Pokemon ist.",
    567: "Bevor es abhebt, nimmt es am Boden Anlauf. Es ist schlau genug, seine Beute zusammen mit Artgenossen zu jagen.",
    568: "Eine Muelltuete, der Industrieabfaelle und chemische Reaktionen neues Leben eingehaucht haben.",
    569: "Es nimmt mit dem rechten Arm Gegner in die Mangel und gibt ihnen mit dem giftigen Gas aus seinem Maul den Rest.",
    570: "Nicht selten ueberrumpelt es Gegner, indem es ihre Gestalt annimmt und den Ueberraschungseffekt zur Flucht nutzt.",
    571: "Kann auf einen Schlag grosse Massen von Menschen taeuschen. Es kreiert Illusionen, um sein Revier zu schuetzen.",
    572: "Sie begruessen einander, indem sie ihr Gegenueber mithilfe ihres Schweifs saeubern.",
    573: "Sein weisser Flaum fuehlt sich wunderbar flauschig an und zieht weder Staub noch statische Elektrizitaet an.",
    574: "Die schleifenfoermigen Fuehler erhoehen seine Psycho-Kraefte. Es scheint stets irgendetwas anzustarren.",
    575: "Zieht seine Energie aus dem Sternenlicht. Bei Nacht bringt es Steine zum Schweben und bildet damit Sternzeichen nach.",
    576: "Durch seine maechtigen Psycho-Kraefte kruemmt sich der Raum und Bilder eines Lichtjahre entfernten Ortes erscheinen.",
    577: "Die spezielle Fluessigkeit, die es umgibt, bietet ihm in jeder noch so gefaehrlichen Situation Schutz.",
    578: "Wegen seines gespaltenen Denkapparates kann es vorkommen, dass es sich abrupt einer anderen Taetigkeit zuwendet.",
    579: "Seine Arme bestehen aus einer speziellen Fluessigkeit. Dank seiner Psycho-Kraefte kann es mit ihnen Felsen zerschmettern.",
    580: "Geraet es in Gefahr, versprueht es Wasser aus seinem Federkleid und nutzt den Spruehregen, um Reissaus zu nehmen.",
    581: "Sie wirken zerbrechlich, aber ihre starken Schwingen tragen sie in einem Stueck bis zu 1 000 km weit.",
    582: "Die Temperatur seines Odems liegt bei -50 Grad. Es erzeugt Eiskristalle und laesst es in seiner Umgebung schneien.",
    583: "Es produziert Eiskoerner, indem es die Luft um sich herum abkuehlt, und zieht mit ihnen eine Eisschicht um seinen Gegner.",
    584: "Bringt man beide Koepfe in Rage, stoesst sein Horn heftige Eisboeen aus, und alles in seiner Umgebung versinkt in Schnee.",
    585: "Unabhaengig von der Jahreszeit aendert sich seine Farbe auch bei wechselnder Temperatur oder Luftfeuchtigkeit leicht.",
    586: "An seinem Geweih kann man ablesen, wann eine neue Jahreszeit beginnt. Sein Revier wechselt mit jeder neuen Jahreszeit.",
    587: "Lebt in den Wipfeln der Waldbaeume. Waehrend es durch die Luefte gleitet, entlaedt es Strom aus seinen Fluglappen.",
    588: "Ein mysterioeses Pokemon, das sich entwickelt, wenn es zusammen mit Schnuthelm einen Stromschlag abbekommt.",
    589: "Eine von einem Schnuthelm gestohlene Muschel dient ihm als Helm. Es greift Gegner mit seinen beiden Lanzen an.",
    590: "Faellt ein Trainer auf sein Aeusseres herein, das komischerweise einem Pokeball aehnelt, besprueht es ihn mit Giftsporen.",
    591: "Um Beute anzulocken, bietet es seinen Hut feil, der einem Pokeball aehnelt. Doch kaum ein Pokemon faellt darauf herein.",
    592: "Es laehmt seine Beute mit Gift und verschleppt sie in seinen Unterschlupf, 8 km unter dem Meeresspiegel.",
    593: "Es heisst, am Meeresboden gebe es einen Palast aus Schiffen, die es versenkt hat. Es besteht fast nur aus Meerwasser.",
    594: "Es treibt durch den Ozean. Findet es ein verletztes Pokemon, nimmt es dieses auf und traegt es zurueck an Land.",
    595: "Da es selbst keinen Strom erzeugen kann, klettert es auf andere Pokemon, um ihnen elektrostatische Energie abzusaugen.",
    596: "Laesst seine Beute in elektrisch geladene Faeden tappen. Solang diese durch den Schock gelaehmt ist, labt es sich an ihr.",
    597: "Fuehlt es sich bedroht, wehrt es sich, indem es eine grosszuegige Salve Dornen abfeuert.",
    598: "Es macht mit Gegnern kurzen Prozess, indem es mit seinen drei Schlingen auf sie eindrischt und Dornen auf sie abfeuert.",
    599: "Es gewinnt lebenswichtige Energie, indem es seine zwei Einzelteile ineinander verzahnt und rotieren laesst.",
    600: "Teilt Artgenossen seine Gefuehlslage mit, indem es die Umlaufrichtung aendert. Wenn es wuetend ist, dreht es sich schneller.",
    601: "Indem es das Rad mit dem roten Zentrum mit hohem Tempo zum Rotieren bringt, kann es eine Turboladung durchfuehren.",
    602: "Allein erzeugt es nur wenig Strom, doch tritt es geschlossen im Schwarm auf, gleicht seine Kraft der eines Blitzes.",
    603: "Schlingt sich um Gegner, laehmt sie ueber die rund gemaserten Flaechen an seinem Koerper mit Strom und beisst beherzt zu.",
    604: "Mit dem Saugnapf an seinem Maul hakt es sich an seiner Beute fest und versetzt ihr ueber seine Fangzaehne Stromschlaege.",
    605: "Es verfuegt ueber maechtige Psycho-Kraefte, mit denen es die Hirne seiner Gegner verwirrt, um ihnen Kopfweh zu bereiten.",
    606: "Es spricht, indem es seine Fingerspitzen leuchten laesst, doch noch konnte der Code dahinter nicht entziffert werden.",
    607: "Es entzuendet ein Licht und gibt vor, dem Gegner den Weg zu weisen, doch eigentlich saugt es ihm seine Lebensenergie ab.",
    608: "Es naehrt seine Flamme mit den Seelen seiner Opfer. Heutzutage irrt es auf der Suche nach Seelen durch Krankenhaeuser.",
    609: "Es saugt die Seele eines jeden auf, der in seinen Feuerkranz geraet, bis nur noch eine leere Huelle von ihm uebrig ist.",
    610: "Es knackt mit seinen Hauern Nuesse. Brechen seine Fangzaehne ab, waechst an ihrer Stelle ein staerkeres Ersatzpaar.",
    611: "Mit seinen Faengen kriegt es sogar Felsen klein. Gegen Artgenossen, die sein Revier passieren, geht es besonders hart vor.",
    612: "Hat eine eher sanfte Natur, doch bei Eindringlingen kennt es keine Gnade. Seine Stosszaehne durchbohren sogar Eisen.",
    613: "Der Schleim, der stets aus seiner Nase haengt, treibt seine Attacken an. Zieht es ihn hoch, steht ein Angriff bevor.",
    614: "Es liebt die kalten Meere im Norden und ueberquert ihre Flaechen auf Stegen, die es mit seinem gefrorenen Atem baut.",
    615: "Es faengt seine Beute mit Ketten, die sich aus Eiskristallen zusammensetzen. Entstanden ist es aus einer Schneewolke.",
    616: "Haelt sich ein Laukaps in seiner Naehe auf und kommen beide mit Strom in Beruehrung, entwickeln sie sich.",
    617: "Seit es die schwere Muschel abgestreift hat, ist es viel leichter. Nun gleichen seine Kampfbewegungen denen eines Ninja.",
    618: "Dank seiner dicken Haut haelt es selbst das Gewicht eines Sumoringers aus. Wenn es Stromschlaege verteilt, grinst es.",
    619: "Schnelle Angriffe sind seine Spezialitaet. Es gleicht seine Schwaechen mit der Vielfalt seines Attackenrepertoires aus.",
    620: "Es benutzt das Fell an seinen Armen als Peitsche. Beide Arme bewegen sich dabei mit atemberaubender Geschwindigkeit.",
    621: "Es jagt durch enge Hoehlengaenge und spiesst seine Gegner mit spitzen Klauen auf. Seine Kopfhaut ist fester als Stein.",
    622: "Es wird durch eine Energie angetrieben, die seinem Koerper entspringt. Keiner weiss jedoch, woher diese Energie stammt.",
    623: "Man munkelt, sein Schoepfer habe ihm aufgetragen, schuetzend ueber Pokemon und Menschen zu wachen.",
    624: "Sein Koerper ist mit Klingen uebersaet, die es an Felsen eines Flussbettes schaerft, wenn sie im Kampf schartig werden.",
    625: "Ein kaltbluetiges Pokemon, das Gegner zunaechst mit einer Schar von Gladiantri laehmt und dann zweiteilt.",
    626: "Rammt seine Gegner ohne Ruecksicht auf Verluste mit dem Kopf und vermag damit sogar Zuege zum Entgleisen zu bringen.",
    627: "Kann mit seinen Fuessen Nuesse zermalmen. Es stellt sich jedem noch so starken Gegner tapfer zum Kampf.",
    628: "Ein tapferer Krieger der Luefte, der zum Schutz seiner Kameraden auch mit Verletzungen immer weiterkaempft.",
    629: "Seine Fluegel sind noch zu klein zum Fliegen. Kurz bevor es sich entwickelt, wirft es seine Schaedelwindel ab.",
    630: "Es kreist am Himmel, bis es seine Beute findet. Nach erfolgtem Angriff traegt es sie muehelos zu seinem Nest.",
    631: "Mit seiner brandheissen Zunge bringt es Fermicula zum Schmelzen, um so an sein weiches Inneres zu gelangen.",
    632: "Eine ausgekluegelte Rollenverteilung hilft ihnen dabei, ihren natuerlichen Feind Furnifrass aus dem Nest zu verjagen.",
    633: "Da es nichts sehen kann, sucht es seine Umgebung mit Rempel- und Bissattacken ab und ist immer mit Wunden uebersaet.",
    634: "Seine zwei Koepfe sind sich spinnefeind. Beide versuchen, ueber Fresswettbewerbe die Oberhand zu gewinnen.",
    635: "Die Koepfe an seinen beiden Armen haben kein eigenes Gehirn. Seine drei Maeuler kauen alles radikal kurz und klein.",
    636: "Es heisst, es sei ein Produkt der Sonne. Wenn es sich entwickelt, huellt es sich in Flammen, die es aus seinen Hoernern blaest.",
    637: "Schuettelt sich gluehenden Staub aus seinen sechs Fluegeln und verwandelt das Umfeld in ein einziges Meer aus Flammen.",
    638: "Sein Koerper und sein Herz sind aus Stahl. Ein boeser Blick genuegt und selbst die wildesten Pokemon unterwerfen sich ihm.",
    639: "Seine Angriffskraft genuegt, um selbst maechtige Waelle niederzureissen. Ein Held zahlreicher Legenden.",
    640: "Das Horn an seinem Kopf ist eine scharfe Klinge. Neckt seine Gegner mit quirligen Bewegungen und greift blitzartig an.",
    641: "Sein Unterkoerper ist in eine wolkenartige Energieschicht gehuellt. Es jagt mit bis zu 300 km/h durch die Luefte.",
    642: "Es greift mit elektrischer Ladung aus den Dornen seiner Rute an und bombardiert Einall aus der Luft mit Blitzen.",
    643: "Ein Legendaeres Pokemon mit der Macht, die Welt mit seinen Flammen einzuaeschern. Hilft allen, die nach Wirklichkeit streben.",
    644: "Ein Legendaeres Pokemon mit der Macht, die Welt durch Donner einzuaeschern. Hilft allen, die einer Welt der Wuensche harren.",
    645: "Da an Orten, wo es sich blicken laesst, mit reicher Ernte zu rechnen ist, nennt man es auch den \"Herrn des Ackerbaus\".",
    646: "Ein Legendaeres Eis-Pokemon, das auf den Helden wartet, der seinen verstuemmelten Koerper mit Wunsch und Wirklichkeit heilt.",
    647: "Es kann auf dem Wasser laufen und reist auf Fluessen und Meeren um die Welt. Zu sehen in malerischen Kuestengebieten.",
    648: "Es besitzt die Macht, Pokemon, die sich in seiner Naehe aufhalten, mit seinen Melodien froh oder traurig zu stimmen.",
    649: "Ein von Team Plasma modifiziertes Kaefer-Pokemon aus dem Altertum. Die Kanone auf seinem Ruecken ist nun noch staerker.",
}
